# Generated by Django 2.2.2 on 2019-06-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2papp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='layerone',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='layertwo',
        ),
        migrations.AddField(
            model_name='slider',
            name='layer_one',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='layer_two',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='layer_two_span',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='layerone_span',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
