# Generated by Django 2.2.2 on 2019-06-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2papp', '0002_auto_20190614_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='layer_one',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name'),
        ),
    ]
