# Generated by Django 2.2.2 on 2019-06-29 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('p2papp', '0003_auto_20190620_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('fund_needed', models.CharField(max_length=20)),
                ('funds_collected', models.CharField(max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation', models.IntegerField()),
                ('payment_method', models.CharField(max_length=2)),
                ('invester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2papp.Investor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2papp.Project')),
            ],
        ),
    ]
