# Generated by Django 2.2.2 on 2019-06-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2papp', '0004_fund_investor_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='fund_needed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='funds_collected',
            field=models.IntegerField(),
        ),
    ]
