# Generated by Django 2.2.2 on 2019-06-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2papp', '0005_auto_20190629_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='donation',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='fund_needed',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='funds_collected',
            field=models.BigIntegerField(),
        ),
    ]
