# Generated by Django 2.2.2 on 2019-06-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2papp', '0006_auto_20190629_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='funds_collected',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
