# Generated by Django 2.2.2 on 2019-06-30 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p2papp', '0007_auto_20190629_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2papp.Project')),
            ],
        ),
    ]
