# Generated by Django 2.2.2 on 2019-06-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2papp', '0009_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='funds_collected',
            field=models.BigIntegerField(blank=True, default=0.0, null=True),
        ),
    ]
