# Generated by Django 2.2.2 on 2019-06-30 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p2papp', '0011_auto_20190630_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='funds_collected',
        ),
    ]
