# Generated by Django 2.2.2 on 2019-07-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2papp', '0013_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pre_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
